### ISSUE TITLE
State goes from Establishing to Terminated while joining a meeting

### ISSUE THREAD

**Issue by dmklementiev** [microsoft/Broadcast-Development-Kit#32]
This is follow up on [this issue](https://github.com/microsoft/Broadcast-Development-Kit-Web-UI/issues/26).  I've double checked appSettings.local.json (Ngrok part) - values seem to be correct , and  the cert - it's registered and CertificateThumbprint in appSettings.local.json is correct.  However, I am still seeing the same issue.  Also when I do a POST (last step in [this document](https://github.com/microsoft/Broadcast-Development-Kit/blob/main/docs/how-to-run-the-solution-locally/README.md#gstreamer)), it returns with OK however, the BotService logs show the same failure:

`[14:00:03 INF] Executing action method BotService.Controllers.BotController.OnIncomingRequestAsync (BotService) - Validation state: Valid
[14:00:03 INF] Executed action method BotService.Controllers.BotController.OnIncomingRequestAsync (BotService), returned result Microsoft.AspNetCore.Mvc.OkObjectResult in 118.5003ms.
[14:02:31 INF] [CallHandler] On updated call - Old State Establishing - New State Terminated`

Please advice how I can debug this further.

**Comment by JonatanMedinilla** [comment]
Hi @dmklementiev, I hope you are doing great. I reviewed the issue you created in the Web UI repository and as @sw-dcherubini  said when the call status changes from **Establishing** to **Terminated** it usually means that the Graph API wasn't able to complete the handshake with the Bot. It often happens because we completed wrong the **appSettings** with the Ngrok settings or the Ngrok session has issues, and if it's the last case we shut down Ngrok and create a new session again.

Regarding the Invite Bot POST request you did, the _Call Initialization / Bot Invitation_ process is not synchronous. This means that when you do the request, you start the _Call Initialization / Bot Invitation_ process, the API returns a 200 OK Status Code because the process has been correctly started, but the BotService starts the handshake process with the Microsoft Graph API in the background. When this handshake process starts, the BotService starts to receive and process notifications from Microsoft Graph API, and if for some reason the call wasn't established, it updates the status to **Terminated**; so to check the actual status of a call, we need to do a GET request to the endpoint _https://localhost:8442/api/call/{callId}_.

Because we don't have control over the platform we rely on to establish the communication with Microsoft Graph API, something you can do to troubleshoot is to check an endpoint we left in the bot for this type of scenario to check the Microsoft Graph API logs_https://localhost:9442/api/bot/logs. Then you can provide us the log response, the configuration you used during that test (without sensitive information) and a screenshot of the terminal where you ran the Ngrok session to see the info about the session. If the log shows an error related to Microsoft Graph API, we can tell you the GitHub repository where you can ask for help.

While answering the issue, I've taken some time to try to force this scenario, and the way to do that was to introduce a wrong _serviceFqdn_. In the picture below you can see that the number I've in my DNS as a record to map _4.mydomain.co_ to _4.tcp.ngrok.io_ doesn't match with the Ngrok one.

![image](https://user-images.githubusercontent.com/23441277/132708170-28162874-c7fb-48bf-8898-2d28ac8e0a06.png)


Below I'm sharing just a portion of the log that I got using the endpoint that I mentioned, where we can see a Graph notification for the call resource that indicates that the state is **Terminated** due to the error _code 500 - subcode - 7112 - message: MediaControllerConversationAddParticipantFailed_. I've found a related [issue ](https://github.com/MicrosoftDocs/msteams-docs/issues/1157) for this case in one of the Microsoft Docs repositories (If you want to check the repository with examples of bots we used to create our bot, you can check [this one](https://github.com/microsoftgraph/microsoft-graph-comms-samples)) and one of the contributors [mentioned ](https://github.com/MicrosoftDocs/msteams-docs/issues/1157#issuecomment-557619174) that the issue could be related to the Ngrok configuration (ports, CNAME) or the [certificate ](https://github.com/MicrosoftDocs/msteams-docs/issues/1157#issuecomment-557666874).

```json $>2021-09-09T14:43:38.9318617Z Info: CommunicationsClientExtensions.cs:156 LogAndCreateResponse
ScenarioId: 024a220a-f98a-4eb6-8d91-ba26a2cf7ad7
AppId: 5b2b0743-b7e6-4110-87c1-3235908b254d
AppName: BotService
TransactionDirection: Incoming
TraceType: HttpRequest
request: POST http://d3d0-2800-810-510-81ae-9ce8-6dd-321e-d718.ngrok.io/api/bot/calling
headers:
  Accept: application/json
  Accept-Encoding: (redacted)
  Authorization: (redacted)
  Host: d3d0-2800-810-510-81ae-9ce8-6dd-321e-d718.ngrok.io
  User-Agent: Microsoft-Skype/3.0,(Calling/1.0)
  Scenario-Id: 024a220a-f98a-4eb6-8d91-ba26a2cf7ad7
  X-Forwarded-For: (redacted)
  X-Forwarded-Proto: https
  X-Microsoft-Skype-Chain-Id: 032c3e81-4602-4864-98d4-4f4b755e4ea3
  X-Microsoft-Skype-Message-Id: 2264cb70-c2e3-4ba7-b1a0-6500bac33696
{
  "@odata.type": "#microsoft.graph.commsNotifications",
  "value": [
    {
      "@odata.type": "#microsoft.graph.commsNotification",
      "changeType": "deleted",
      "resourceUrl": "/communications/calls/7e1f5100-2820-468c-a3ef-43e556976a71",
      "resource": "/app/calls/7e1f5100-2820-468c-a3ef-43e556976a71",
      "resourceData": {
        "@odata.type": "#microsoft.graph.call",
        "state": "terminated",
        "resultInfo": {
          "@odata.type": "#microsoft.graph.resultInfo",
          "code": 500,
          "subcode": 7112,
          "message": "MediaControllerConversationAddParticipantFailed"
        },
        "chatInfo": {
          "@odata.type": "#microsoft.graph.chatInfo",
          "threadId": "19:meeting_NmZiZTNlZGYtNjM4Ni00ZTZiLWJlYzAtY2MxMDkwMTBmN2Q5@thread.v2",
          "messageId": "0"
        },
        "meetingInfo": {
          "@odata.type": "#microsoft.graph.organizerMeetingInfo",
          "organizer": {
            "@odata.type": "#microsoft.graph.identitySet",
            "user": {
              "@odata.type": "#microsoft.graph.identity",
              "id": "62dd499c-9840-45eb-9e04-72d9c2460dc5",
              "tenantId": "b25036e3-de39-4fec-a4aa-bda41b870d38"
            }
          }
        },
        "tenantId": "b25036e3-de39-4fec-a4aa-bda41b870d38",
        "callChainId": "032c3e81-4602-4864-98d4-4f4b755e4ea3",
        "id": "7e1f5100-2820-468c-a3ef-43e556976a71"
      }
    }
  ]
}```

**Comment by dmklementiev** [comment]
This should have been the certificate.  After I re-generated it and re-registered it the "Terminated" message went away, but I am facing a new one - https://github.com/microsoft/Broadcast-Development-Kit/issues/34.

Closing this issue.
